sudo: false
language: java
jdk:
  - oraclejdk8
env:
    - MAVEN_OPTS="-Xms2048m -Xmx=2048m"
script: "./run-tests.sh"
addons:
  postgresql: "9.4"
before_script:
  - psql -c 'create database sqlgraphdb;' -U postgres
  - psql -c 'create database g1;' -U postgres
  - psql -c 'create database g2;' -U postgres
  - psql -c 'create database prototype;' -U postgres
  - psql -c 'create database readGraph;' -U postgres
  - psql -c 'create database standard;' -U postgres
  - psql -c 'create database subgraph;' -U postgres
  - psql -c 'create database temp;' -U postgres
  - psql -c 'create database temp1;' -U postgres
  - psql -c 'create database temp2;' -U postgres

